var activity=
[


{"name" : "Tennis Equipment "},
{"name" : "Water Park"},
{"name" : "Badminton Equipment"},
{"name" : "Water Sports Facilities (on site) "},
{"name" : "Beach"},
{"name" : "Windsurfing"},
{"name" : "Tennis Court "},
{"name" : "Diving "},
{"name" : "Pool Table"},
{"name" : "Snorkeling"},
{"name" : "Ping-Pong"},
{"name" : "Canoeing"},
{"name" : "Darts "},
{"name" : "Fishing"},
{"name" : "Racquetball "},
{"name" : "Horseback Riding "},
{"name" : "Bowling"},
{"name" : "Cycling"},
{"name" : "Mini Golf "},
{"name" : "Hiking "},
{"name" : "Golf Course (within 2 miles)"},
{"name" : "Skiing"},

];



var Food and Drink=[
{"name" : "Kids' Meals "},
{"name" : " Bar "},
{"name" : "Kid-Friendly Buffet "},
{"name" : "Snack Bar"},
{"name" :"Wine/Champagne"},
{"name" :"Grocery Deliveries "},
{"name" :"Bottle of Water "},
{"name" : "Packed Lunches"},
{"name" : " Fruit"},
{"name" : "BBQ Facilities"},
{"name" : "Chocolate/Cookies"},
{"name" : "Chocolate/Cookies"},
{"name" : "On-site Coffee Shop "},
{"name" : "Vending Machine (snacks) "},
{"name" : "Restaurant "},
{"name" : "Special Diet Meals (upon request)"},
{"name" : "Restaurant With Dining Menu"},
{"name" : "Room Service"},
{"name" : "Buffet-Style Restaurant"},
{"name" : "Breakfast in the Room"},

];

var Pool & Spa=[
{"name" : "Waterslide"},
{"name" : "Personal Trainer"},
{"name" : "Pool Towels "},
{"name" : "Fitness/Spa Locker Rooms "},
{"name" : "Beach Chairs/Loungers"},
{"name" : "Kids' Pool"},
{"name" : "Beach Umbrellas "},
{"name" : "Swimming Pool "},
{"name" : " Beauty Services"},
{"name" : "Spa"},
{"name" : "Spa Facilities"},
{"name" : "Sauna"},
{"name" : "Steam Room "},
{"name" : "Turkish/Steam Bath"},
{"name" : "Spa Lounge/Relaxation Area "},
{"name" : "Hot Tub/Jacuzzi"},
{"name" : "Foot Bath"},
{"name" : "Fitness Center"},
{"name" : "Spa/Wellness Packages"},
{"name" : "Solarium"},
{"name" : "Massage Chair"},
{"name" : "Hot Spring Bath"},
{"name" : "Fitness"},
{"name" : "Massage"},
{"name" : "Yoga Classes"},
{"name" : "Open-air Bath"},
{"name" : "Fitness Classes"},
{"name" : "Bathhouse"},


];

var Transportation=[
{"name" : " Secured Parking"},
{"name" : "Shuttle Service"},
{"name" : "Street Parking "},
{"name" : "Bikes Available (free) "},
{"name" : "Parking Garage"},
{"name" : "Bicycle Rental (additional charge)"},
{"name" : "Electric Vehicle Charging Station "},
{"name" : "Car Rental"},
{"name" : "Public Transportation Tickets "},
{"name" : "Airport Shuttle"},
{"name" : "Accessible Parking"},

];

var Front Desk Services=[
{"name" : "Tickets to Attractions or Shows"},
{"name" : "Tour Desk"},
{"name" : "24-Hour Front Desk "},
{"name" : "Shuttle Service"},
{"name" : "Private Check-in/Check-out"},
{"name" : "Bikes Available (free) "},
{"name" : "Bicycle Rental (additional charge)"},
{"name" : "Concierge Service"},
{"name" : "Car Rental"},
{"name" : "Ticket Service"},
{"name" : "Airport Shuttle"},

];


var Common Areas=[
{"name" :"Outdoor Furniture"},
{"name" : " Shared Kitchen"},
{"name" : "Picnic Area"},
{"name" : "Shared Lounge/TV Area "},
{"name" : "Outdoor Fireplace"},
{"name" : "Game Room"},
{"name" : "Grounds"},
{"name" : "Library"},
{"name" : "Terrace"},
{"name" : "Chapel/Shrine"},
{"name" : "Sun Deck"},


];

var Cleaning Services=[
{"name" : "Dry Cleaning"},
{"name" : "Daily Housekeeping"},
{"name" : "Ironing Service"},
{"name" : "Shoeshine"},
{"name" : "Laundry"},
{"name" : "Suit Press"},



];




var Business Facilities=[


{"name" : "Meeting/Banquet Facilities"},
{"name" : "Fax/Photocopying"},
{"name" : "Business Center"},

];



var Shops=[

{"name" : "Shops (on site)"},
{"name" : "Hair/Beauty Salon"},
{"name" : "Convenience Store (on site)"},
{"name" : "Souvenir/Gift Shop"}
];

var Miscellaneous=[
{"name" :"Pet Basket"},
{"name" :"Elevator"},
{"name" :"Pet Bowls"},
{"name" :"Family Rooms"},
{"name" :"Adults Only"},
{"name" :"Soundproof Rooms"},
{"name" :"Hypoallergenic Room Available"},
{"name" :"Honeymoon Suite"},
{"name" :"All Spaces Non-Smoking (public and private)"},
{"name" :"VIP Room Facilities"},
{"name" :"Designated Smoking Area"},
{"name" :"Air Conditioning"},
{"name" :"Non-Smoking Rooms"},
{"name" :"Heating"},
{"name" :"Facilities for Disabled Guests"},
];

var country=[
{"name" :"Afghanistan"},
{"name" : "Albania"},
{"name" : "Algeria"},
{"name" : "American Samoa"},
{"name" : "Andorra"},
{"name" : "Angola"},
{"name" : "Angular"},
{"name" : "Antarctica"},
{"name" : "Antigua And Barbuda"},
{"name" : "Argentina"},
{"name" : "Armenia"},
{"name" : "Aruba"},
{"name" : "Australia"},
{"name" : "Austria"},
{"name" : "Azerbaijan"},
{"name" : "Bahamas,"},
{"name" : "Bahrain"},
{"name" : "Bangladesh"},
{"name" : "Barbados"},
{"name" : "Belarus"},
{"name" : "Belgium"},
{"name" : "Belize"},
{"name" : "Benin"},
{"name" : "Bermuda"},
{"name" : "Bhutan"},
{"name" : "Bolivia"},
{"name" : "Bosnia and Herzegovina"},
{"name" : "Botswana"},
{"name" : "Buffet Island"},
{"name" : "Brazil"},
{"name" : "British Indian Ocean Territory"},
{"name" : "Brunei"},
{"name" : "Bulgaria"},
{"name" : "Burkina Faso"},
{"name" : "Burundi"},
{"name" : "Cambodia"},
{"name" : "Cameroon"},
{"name" : "Canada"},
{"name" : "Cape Verde"},
{"name" : "Cayman Islands"},
{"name" : "Central African Republic"},
{"name" : "Chad"},
{"name" : "Chile"},
{"name" : "China"},
{"name" : "China (Hong Kong S.E.)"},
{"name" : "China (Mac au S.E.)"},
{"name" : "Christmas Island"},
{"name" : "Coco's (Keeling) Islands"},
{"name" : "Colombia"},
{"name" : "Comoros"},
{"name" : "Congo"},
{"name" : "Congo, Democratic Republic of the"},
{"name" : "Cook Islands"},
{"name" : "Costa Rica"},
{"name" : "Cote Divorce (Ivory Coast)"},
{"name" : "Croatia (Phrasal)"},
{"name" : "Cuba"},
{"name" : "Cyprus"},
{"name" : "Czech Republic"},
{"name" : "Denmark"},
{"name" : "Djibouti"},
{"name" : "Dominica"},
{"name" : "Dominican Republic"},
{"name" : "East Timor"},
{"name" : "Ecuador"},
{"name" : "Egypt"},
{"name" : "El Salvador"},
{"name" : "Equatorial Guinea"},
{"name" : "Eritrea"},
{"name" : "Estonia"},
{"name" : "Ethiopia"},
{"name" : "Falkland Islands (Is las Malians)"},
{"name" : "Faeroe Islands"},
{"name" : "Fiji Islands"},
{"name" : "Finland"},
{"name" : "France"},
{"name" : "French Guiana"},
{"name" : "French Polynesia"},
{"name" : "French Southern Territories"},
{"name" : "Gabon"},
{"name" : "Gambia, The"},
{"name" : "Georgia"},
{"name" : "Germany"},
{"name" : "Ghana"},
{"name" : "Gibraltar"},
{"name" : "Greece"},
{"name" : "Greenland"},
{"name" : "Grenada"},
{"name" : "Guadeloupe"},
{"name" : "Guam"},
{"name" : "Guatemala"},
{"name" : "Guinea"},
{"name" : "Guyana"},
{"name" : "Haiti"},
{"name" : "Heard and McDonald Islands"},
{"name" : "Honduras"},
{"name" : "Hungary"},
{"name" : "Iceland"},
{"name" : "India"},
{"name" : "Indonesia"},
{"name" : "Iran"},
{"name" : "IraqIreland"},
{"name" : "Italy"},
{"name" : "Jamaica"},
{"name" : "Japan"},
{"name" : "Jordan"},
{"name" : "Kazakhstan"},
{"name" : "Kenya"},
{"name" : "Kiribati"},
{"name" : "Korea"},
{"name" : "Korea, North"},
{"name" : "Kuwait"},
{"name" : "Kurdistan"},
{"name" : "Laos"},
{"name" : "Latvia"},
{"name" : "Lebanon"},
{"name" : "Lesotho"},
{"name" : "Liberia"},
{"name" : "Libya"},
{"name" : "Liechtenstein"},
{"name" : "Lithuania"},
{"name" : "Luxembourg"},
{"name" : "Macedonia, Former Yugoslav Republic of"},
{"name" : "Madagascar"},
{"name" : "Malawi"},
{"name" : "Malaysia"},
{"name" : "Maldives"},
{"name" : "Mali"},
{"name" : "Malta"},
{"name" : "Marshall Islands"},
{"name" : "Martinique"},
{"name" : "Mauritania"},
{"name" : "Mauritius"},
{"name" : "Maypole"},
{"name" : "Mexico"},
{"name" : "Micronesia"},
{"name" : "Moldova"},
{"name" : "Monaco"},
{"name" : "Mongolia"},
{"name" : "Monterrey"},
{"name" : "Morocco"},
{"name" : "Mozambique"},
{"name" : "Myanmar"},
{"name" : "Namibia"},
{"name" : "Nauru"},
{"name" : "Nepal"},
{"name" : "Netherlands Antilles"},
{"name" : "Netherlands, The"},
{"name" : "New Caledonia"},
{"name" : "New Zealand"},
{"name" : "Nicaragua"},
{"name" : "Niger"},
{"name" : "Nigeria"},
{"name" : "Unique"},
{"name" : "Norfolk Island"},
{"name" : "Northern Mariana Islands"},
{"name" : "Norway"},
{"name" : "Oman"},
{"name" : "Pakistan"},
{"name" : "Palau"},
{"name" : "Palestine"},
{"name" : "Panama"},
{"name" : "Papua new Guinea"},
{"name" : "Paraguay"},
{"name" : "Peru"},
{"name" : "Philippines"},
{"name" : "Pitcairn Island"},
{"name" : "Poland"},
{"name" : "Portugal"},
{"name" : "Puerto Rico"},
{"name" : "Qatar"},
{"name" : "Reunion"},
{"name" : "Romania"},
{"name" : "Russia"},
{"name" : "Rwanda"},
{"name" : "Saint Helena"},
{"name" : "Saint Kitts And Nevis"},
{"name" : "Saint Lucia"},
{"name" : "Saint Pierre and Miguel"},
{"name" : "Saint Vincent And The Grenadines"},
{"name" : "Samoa"},
{"name" : "San Marino"},
{"name" : "Sao Tome and Principe"},
{"name" : "Saudi Arabia"},
{"name" : "Senegal"},
{"name" : "Seychelles"},
{"name" : "Sierra Leone"},
{"name" : "Singapore"},
{"name" : "Slovakia"},
{"name" : "Slovenia"},
{"name" : "Solomon Islands"},
{"name" : "Somalia"},
{"name" : "South Africa"},
{"name" : "South Georgia And The South Sandwich Islands"},
{"name" : "Spain"},
{"name" : "Sri Lanka"},
{"name" : "Sudan"},
{"name" : "Suriname"},
{"name" : "Sailboard And Jan Ma yen Islands"},
{"name" : "Swaziland"},
{"name" : "Sweden"},
{"name" : "Switzerland"},
{"name" : "Syria"},
{"name" : "Taiwan"},
{"name" : "Tajikistan"},
{"name" : "Tanzania"},
{"name" : "Thailand"},
{"name" : "Togo"},
{"name" : "Toke lau"},
{"name" : "Tonga"},
{"name" : "Trinidad And Tobago"},
{"name" : "Tunisia"},
{"name" : "Turkey"},
{"name" : "Turkmenistan"},
{"name" : "Turks And Calicos Islands"},
{"name" : "Tuvalu"},
{"name" : "Uganda"},
{"name" : "Ukraine"},
{"name" : "United Arab Emirates"},
{"name" : "United Kingdom"},
{"name" : "United States"},
{"name" : "United States Minor Outlying Islands"},
{"name" : "Uruguay"},
{"name" : "Uzbekistan"},
{"name" : "Vanuatu"},
{"name" : "Vatican City State (Holy See)"},
{"name" : "Venezuela"},
{"name" : "Vietnam"},
{"name" : "Virgin Islands (British)"},
{"name" : "Virgin Islands (US)"},
{"name" : "Wallis And Fu tuna Islands"},
{"name" : "Western Sahara"},
{"name" : "Yemen"},
{"name" : "Yugoslavia"},
{"name" : "Zambia"},
{"name" : "Zimbabwe"},



];